#!/usr/bin/env bash

set -eEuCo pipefail
echo "1 is " $1
echo "2 is " $2

declare -r file=$1
declare -i -r line=$2
declare -i -r lines=$((LINES / 2))

# subtract 3 for the header
declare -i center=$(( (lines - 3) / 2 ))

if [ $line -lt $center ]; then
    center=$line
fi
declare -i -r start=$(( line - center ))
declare -i -r end=$(( lines + start ))
echo line=$line center=$center lines=$lines start=$start
echo range is $start:$end

exec bat --color always --highlight-line $line --line-range $start:$end --paging never "$file"
